version: "3"
services:
  devops:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: tail -f /dev/null
  portainer:
    image: portainer/portainer-ce:latest
    container_name: my_portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
